---
title: "Day5Comp1"
format: 
  html:
    code-fold: true
    code-summary: "Show me the code!"
editor: visual
execute:
  echo: true
  warning: false
---

## Probability

```{r}
library(tidyverse)
```

## Explore the starwars dataset

-   look at the first 6 lines of starwars

-   find the dimensions of starwars

-   make a histogram of character heights

-   make a scatterplot of height vs weight

```{r}
head(starwars)
```

```{r}
dim(starwars)
```

```{r}
ggplot(data = starwars, aes(x = height))+
  geom_histogram()
```

```{r}
ggplot(data = starwars, aes(x=height,y=mass, color = species))+
  geom_point(shape = 8)+
  theme_minimal()
```

## Calculate Summary Statistics

use mean() function to find means.

Use sd() function to find standard deviations.

```{r}
mean_height <- mean(starwars$height)
#shows up as NA because some heights are NA, default in mean() is na.rm = FALSE
mean_height <- mean(starwars$height, na.rm = TRUE)
```

Find and store the standard deviation of character heights

```{r}
sd_height <- sd(starwars$height, na.rm = TRUE)
```
